version: "3.9"
services:
    web:
        build: .
        ports:
            - "5024:80"
        depends_on:
            - db
    db:
        ports:
            - "14331:1433"
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "@someThingComplicated1234"
            ACCEPT_EULA: "Y"